#▀███▀▀▀██▄    ▀████▀████▀███▀▀▀██▄                                      
#  ██    ▀██▄    ██   ██   ██    ▀██▄                                    
#  ██     ▀██    ██   ██   ██     ▀█████▄███  ▄██▀██▄▀████████▄   ▄▄█▀██ 
#  ██      ██    ██   ██   ██      ██ ██▀ ▀▀ ██▀   ▀██ ██    ██  ▄█▀   ██
#  ██     ▄██    ██   ██   ██     ▄██ ██     ██     ██ ██    ██  ██▀▀▀▀▀▀
#  ██    ▄██▀██  ██   ██   ██    ▄██▀ ██     ██▄   ▄██ ██    ██  ██▄    ▄
#▄████████▀  █████  ▄████▄████████▀ ▄████▄    ▀█████▀▄████  ████▄ ▀█████▀     

# Fichier de configuration

api_key: ""
map_key: ""
